/*
 * Per-op backward validation against PyTorch autograd references.
 * Reads backward_refs.bin generated by gen_backward_refs.py.
 *
 * usage: ./test_backward_ops backward_refs.bin
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "pt_backward_ops.h"
#include "pt_ops.h"

/* Must match gen_backward_refs.py */
#define DIM   16
#define HDIM  32
#define HD    4
#define VOCAB 64

static int pass_count, fail_count;

static float fabsf_(float x) { return x < 0 ? -x : x; }

/* ── binary file helpers ── */

static int read_int(FILE *f) {
    int v;
    if (fread(&v, sizeof(int), 1, f) != 1) {
        fprintf(stderr, "read_int: unexpected EOF\n");
        exit(1);
    }
    return v;
}

static void read_floats(FILE *f, float *buf, int expected_n) {
    int n = read_int(f);
    if (n != expected_n) {
        fprintf(stderr, "read_floats: expected %d, got %d\n", expected_n, n);
        exit(1);
    }
    if ((int)fread(buf, sizeof(float), n, f) != n) {
        fprintf(stderr, "read_floats: short read\n");
        exit(1);
    }
}

/* ── comparison ── */

static int check(const char *name, const float *got, const float *ref,
                 int n, float atol) {
    float max_err = 0.0f;
    int max_idx = 0;
    for (int i = 0; i < n; i++) {
        float err = fabsf_(got[i] - ref[i]);
        if (err > max_err) { max_err = err; max_idx = i; }
    }
    int ok = max_err < atol;
    printf("  %-20s max_err=%.2e (idx %d)  %s\n",
           name, max_err, max_idx, ok ? "PASS" : "FAIL");
    if (ok) pass_count++; else fail_count++;
    return ok;
}

/* ── tests ── */

static void test_rmsnorm(FILE *f) {
    printf("rmsnorm backward:\n");
    float x[DIM], w[DIM], d_o[DIM];
    float d_x_ref[DIM], d_w_ref[DIM];
    float d_x[DIM], d_w[DIM];

    read_floats(f, x, DIM);
    read_floats(f, w, DIM);
    read_floats(f, d_o, DIM);
    read_floats(f, d_x_ref, DIM);
    read_floats(f, d_w_ref, DIM);

    memset(d_x, 0, sizeof(d_x));
    memset(d_w, 0, sizeof(d_w));
    rmsnorm_backward(d_x, d_w, d_o, x, w, DIM);

    check("d_x", d_x, d_x_ref, DIM, 1e-4f);
    check("d_w", d_w, d_w_ref, DIM, 1e-4f);
}

static void test_matmul(FILE *f) {
    printf("matmul backward:\n");
    float W[HDIM * DIM], x[DIM], d_y[HDIM];
    float d_x_ref[DIM], d_W_ref[HDIM * DIM];
    float d_x[DIM], d_W[HDIM * DIM];

    read_floats(f, W, HDIM * DIM);
    read_floats(f, x, DIM);
    read_floats(f, d_y, HDIM);
    read_floats(f, d_x_ref, DIM);
    read_floats(f, d_W_ref, HDIM * DIM);

    memset(d_x, 0, sizeof(d_x));
    memset(d_W, 0, sizeof(d_W));
    matmul_backward_input(d_x, W, d_y, HDIM, DIM);
    matmul_backward_weight(d_W, d_y, x, HDIM, DIM);

    check("d_x (W^T@dy)", d_x, d_x_ref, DIM, 1e-4f);
    check("d_W (dy*x^T)", d_W, d_W_ref, HDIM * DIM, 1e-4f);
}

static void test_rope(FILE *f) {
    printf("rope backward:\n");
    int pos = read_int(f);

    float d_q_out[DIM], d_k_out[DIM];
    float d_q_ref[DIM], d_k_ref[DIM];
    float d_q[DIM], d_k[DIM];

    read_floats(f, d_q_out, DIM);
    read_floats(f, d_k_out, DIM);
    read_floats(f, d_q_ref, DIM);
    read_floats(f, d_k_ref, DIM);

    memset(d_q, 0, sizeof(d_q));
    memset(d_k, 0, sizeof(d_k));
    rope_backward(d_q, d_k, d_q_out, d_k_out, DIM, HD, pos);

    check("d_q", d_q, d_q_ref, DIM, 5e-3f);
    check("d_k", d_k, d_k_ref, DIM, 5e-3f);
}

static void test_softmax(FILE *f) {
    printf("softmax backward:\n");
    float y[DIM], d_y[DIM];
    float d_x_ref[DIM], d_x[DIM];

    read_floats(f, y, DIM);
    read_floats(f, d_y, DIM);
    read_floats(f, d_x_ref, DIM);

    memset(d_x, 0, sizeof(d_x));
    softmax_backward(d_x, d_y, y, DIM);

    check("d_x", d_x, d_x_ref, DIM, 1e-5f);
}

static void test_silu(FILE *f) {
    printf("silu backward:\n");
    float x[DIM], d_y[DIM];
    float d_x_ref[DIM], d_x[DIM];

    read_floats(f, x, DIM);
    read_floats(f, d_y, DIM);
    read_floats(f, d_x_ref, DIM);

    memset(d_x, 0, sizeof(d_x));
    silu_backward(d_x, d_y, x, DIM);

    check("d_x", d_x, d_x_ref, DIM, 1e-4f);
}

static void test_embedding(FILE *f) {
    printf("embedding backward:\n");
    int n_tokens = read_int(f);
    int tokens[16];
    for (int i = 0; i < n_tokens; i++)
        tokens[i] = read_int(f);

    float d_os[16 * DIM];
    for (int i = 0; i < n_tokens; i++)
        read_floats(f, d_os + i * DIM, DIM);

    float d_table_ref[VOCAB * DIM];
    read_floats(f, d_table_ref, VOCAB * DIM);

    float d_table[VOCAB * DIM];
    memset(d_table, 0, sizeof(d_table));
    for (int i = 0; i < n_tokens; i++)
        embedding_backward(d_table, d_os + i * DIM, DIM, tokens[i]);

    check("d_table", d_table, d_table_ref, VOCAB * DIM, 1e-5f);
}

/* ── main ── */

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <backward_refs.bin>\n", argv[0]);
        return 1;
    }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 1; }

    printf("=== backward ops tests ===\n\n");

    test_rmsnorm(f);
    test_matmul(f);
    test_rope(f);
    test_softmax(f);
    test_silu(f);
    test_embedding(f);

    fclose(f);

    printf("\n=== %d passed, %d failed ===\n", pass_count, fail_count);
    if (fail_count == 0) printf("ALL PASS\n");
    return fail_count > 0 ? 1 : 0;
}
